good-loop/my-loop

src/js/components/HashWatcher.jsx, src/js/components/MainDiv.jsx, web/index.html
HashWatcher.jsx creates synthetic page URLs in the pattern...
`#my` ⟶ `/my`
`#campaign` ⟶ `/campaign`
`#campaign?gl.vert=xxxxx` ⟶ `/campaign/vert/xxxxx`
`#campaign?gl.campaign=yyyyy` ⟶ `/campaign/cmp/yyyyy`
...and logs changes in this virtual URL to Google Analytics, as (a) hashes aren't logged by the normal Google tag, and (b) hash changes don't automatically trigger a pageview event.
=> Show which campaign pages are being visited in Google Analytics

package.json, src/js/components/campaignpage/Charities.jsx
- Now generically replaces "nouns (singular:noun)" wherever it's found, instead of needing it to occur in a particular structure.
- blahRegex.lastIndex: did you know RegExp objects with the /g flag are stateful, and consecutive calls to exec() have different effects? This resets the regex.
- Can still be broken: the Trussell Trust's impact string "three day emergency food supplies (singular: supply)" doesn't have a verb, which breaks the "To help verb nouns" inversion when impact-count is 0 (you get "To help supplies three day emergency food"). Should we log cases where the (singular: noun) appears at the end of a line and flag those charities to have their impact descriptions fixed (eg "emergency food supplies provided")? Have an extra sentence form triggered by ending-with-noun?
=> Last impact description fix still had bugs.

src/js/components/NewTabMainDiv.jsx
Don't show the "Together we've raised $X" no-charity-selected message until it's known that the user hasn't selected a charity.
=> T4G fix for donation total flicker

src/js/components/CharityLogo.jsx
Hello,
If you visit https://my.good-loop.com/#charities, you can see that some of the links are broken for certain charities (Art Fund and the Meningitis Research Foundation for example). This is a fix for that.
Thanks
=> fix broken hrefs on /#charities

src/js/components/pages/CharityLandingPage.jsx, src/js/components/pages/CommonComponents.jsx
Hello @wongws11,
This will PR will fix the "undefined" name we're seeing for some NGOs, seen here for example: https://my.good-loop.com/charity/eden-reforestation-projects
It'll prefer `ngo.displayName` over `ngo.name`, which should hopefully fix with issues like this too, where `ngo.name` is just the same as the charity ID/slug: https://my.good-loop.com/charity/rmhc
- Aidan
=> prefer ngo.displayName over ngo.name

src/js/components/MainDiv.jsx, src/js/components/pages/AccountPage.jsx
Hello @winterstein,
This PR will move the dashboard / settings / t4g settings links on `/#account` into the Navbar on mobile devices. These will appear under the account menu, between the "Account" and "Logout" items.
There's probably a much more elegant way to achieve what I'm trying to do, please let me know if there's anything I could have done better, it will help me learn. :)
NB: I think this might break something on Firefox (I see `TypeError: itemValue is null` - not 100% sure if it's related), but I can't quite figure out what. It works fine on Chrome. 
See also: [wwappbase.js/pull/83](https://github.com/good-loop/wwappbase.js/pull/83)
=> move account page settings links to navbar dropdown on mobile displays

src/js/components/MainDiv.jsx, src/js/components/NewTabMainDiv.jsx, src/js/components/pages/LogoutPage.jsx
A workaround. 
T4G logout will not work possibly because of HTTPS issue. This workaround redirect the user to my-loop and log them out instantly, redirecting them back to home page of my-loop. 
Good idea?
=> possbile workaround to logout

package.json, src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/dashutils.js
Hello @roscoemcinerney,
This PR will add a download button to each Green Dashboard widget. It uses `html2canvas` to create a canvas element for a given widget, which can then be exported as an image.
Some caveats:
- Sizing isn't consistent. The size of the final image will depend on the browser viewport.
- Text is slightly blurry. `html2canvas` doesn't work well when elements have a `box-shadow` CSS property, they won't render properly. I tried to remove that property in the cloned document, but couldn't get it to work for some reason. I discovered that setting `scale` to `1.25` for, whatever reason, fixes the rendering issue - but this makes some text ever so slightly blurry.
Also not sure how well this will work on mobile.
- Aidan
=> add download button to greendash widgets

src/js/components/pages/greendash/GreenDashboardFilters.jsx
Hello @winterstein,
This will let users filter my agency.
It's a simple change, but I'm not sure if there was a specific reason as to why it was limited to testers so thought I'd best have someone double check before committing straight to master.
Thanks,
Aidan
=> let non-testers filter by agency

src/js/components/pages/greendash/TimeSeriesCard.jsx
@roscoemcinerney ![image](https://user-images.githubusercontent.com/22352872/194869970-3651f353-0485-4ed6-bd4f-b15ed05b11a4.png) Card not in full width. Adding back `w-100` in this line will fix it.
=> timesseriescard w-100

src/js/components/pages/greendash/BreakdownCardEmissions.jsx, src/js/components/pages/greendash/CompareCardEmissions.jsx, src/js/components/pages/greendash/GreenMetricsEmissions.jsx, src/js/components/pages/greendash/JourneyCardEmissions.jsx
There are still room of improvement inside of `BreakdownCardEmissions` but this should already give a huge improvement to the UX by cutting down the initial load time. 
https://my.good-loop.com/greendash?campaign=iLWiEWO6&period=2022-Q4
Speed up the initial loading time of this page from 18+ seconds to within 4 seconds. (BreakdownCard still need 15 seconds to load, but this sub card won't stop from other parts of the dashboard to load anymore)
=> performance update draft

src/js/components/pages/greendash/JourneyCardEmissions.jsx, src/js/components/pages/greendash/emissionscalc.js
Also updated tree calculation to use impressions for selected period, rather than all-time for each campaign.
=> Tree count back on journey card

src/js/components/pages/greendash/GreenDashboardFilters.jsx
The dashboard filter was firing a harmless but alarming console error when it attempted to populate the filter-by-item dropdown before the user selected which type of item to filter on - this guards against that.
=> Green dashboard: silence a console error

src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/JourneyCard.jsx
Before the big precalculated emissions refactor, the "Your Journey" card used to have a table available with a complete all-variables cross-breakdown - and a button to download it. This adds back a CSV download with the same column set.
=> Green dashboard: Restore old columns on CSV export

src/style/navbar.less
Gives the logo a fixed height (SVG logos don't necessarily take up that space without being told) and restricts width on mobile sizes.
=> Fix issue where charity logo shoves hamburger out of navbar

src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/GreenNavBar.jsx, src/js/components/pages/greendash/dashutils.js, src/style/GreenDashboard.less
Puts account menu into the top right and adds flags for the share widget
Not moved the share widget into the account menu for now - was causing bugs with the modal opening twice
Flags:
to show share widget - "shareables=true", or any debug flag
to show emails in share widget - "listemails=true"
to show account menu - any debug or the "shareables" flag
Companion PR in wwappbase.js by the same branch name
=> Bugfix/2023 02/account menu layout

src/js/components/pages/greendash/MapCard.jsx
regions now need > 1% of total emissions to be labeled on map + labels now don't get in the way of countries displaying tooltips
=> greendash map labels overlapping reduced

src/js/components/pages/greendash/JourneyCard.jsx
Changing breakdown from "pub" (almost all unset) to "domain" (many values) makes a too-many-buckets exception from DataLog much more likely, so the export code now also catches that error and suggests the user try a shorter period. (Previous behaviour was to leave the spinner spinning forever)
=> Green dashboard big CSV export - fix unset domains

src/js/components/pages/greendash/MapCard.jsx
potential fix to this issue, copying explanation in from monday: 
"
found the issue, per1000 co2 emissions between regions were far more uniform than the default total co2 emissions. For example, both Austrailia and Kenya have similiar values of ~0.4 kg / 1000, however they have 12,650,775 and 7﻿ impressions ﻿﻿respectively.
﻿
﻿Added a potential fix as if we're in per1000 mode, we convert back into total emissions when checking if a region is responsible for > ﻿1% and if it is, show that regions CO2 / 1000 impressions.
﻿
﻿﻿This approach does mean the map can look a little confusing unless you're aware this is happening as some regions will have drastically higher CO2/1000 but won't be labelled as the total CO2 they aren't responsible for > 1% of the total. A potential fix is to add another …
=> in per1000 mode only show regions with > 1% total emissions

src/js/components/pages/greendash/GreenNavBar.jsx
From a client perspective this looks a little bit off:
This PR will prevent the account menu from showing if you're viewing a dashboard from a shareable link.
=> hide account menu on greendash if logged in as a pseudouser

src/js/components/pages/greendash/GreenMetrics.jsx
We're reporting the wrong numbers at the moment - so temporarily removing the journey card until we release later this week.
@wongws11 @laurenwilso FYI
=> temporarily hide journeycard

src/js/components/impact/ImpactAccountButton.jsx
impact png download feature was breaking greendash downloads. Since it's currently paused while we look into maybe moving away from html2canvas, I've just commented out the part responsible for the change on wwappbase change 
requires: https://github.com/good-loop/wwappbase.js/pull/168
=> feature was breaking greendash png downloads

src/js/components/pages/greendash/JourneyCard.jsx, src/js/components/pages/greendash/TimeSeriesCard.jsx, src/js/components/pages/greendash/emissionscalcTs.ts
Fixes two bugs:
1. Fixed ImpactDebits (i.e. ones where the campaign has finished and the offset is now locked in) were being included regardless of the reporting period. 
2. ImpactDebits that fell outside the reporting period led to an API error (and the logic got stuck at "loading carbon data", hence no number being shown).
Fixed ImpactDebits are now included by fraction of overlap with the reporting period.
=> Feature/2023 04/green dash fix cloud kg

src/js/components/pages/greendash/GreenRecommendation.tsx, web/js-data/generic-domain-emissions.json
This is a proof of concept. No design confirmed. Not to merge. 
The json file were fetch from https://github.com/good-loop/code/blob/master/dataanalysis/src/python/greendata/FetchDomainImpression.ipynb
For now if we add &generic=true at the end of any green recommendation page. The chart will show the overall domain emissions instead of the data from that brand/agency/campaign in that time period. This overall data were fetch from the script https://github.com/good-loop/code/blob/master/dataanalysis/src/python/greendata/FetchDomainImpression.ipynb, simply fetch and cleaned domain emissions from the last 90 days. 
Example link: https://localmy.good-loop.com/greendash/recommendation?emode=total&period=2023-Q2&start=2023-04-01T00%3A00%3A00.000Z&end=2023-07-01T00%3A00%3A00.000Z&tz=UTC&ft=Adver …
=> An option to include a default list of sites in the Green Recs dashboard WIP

src/js/components/impact/GLCards.jsx, src/js/components/pages/greendash/GreenDashUtils.jsx, src/js/components/pages/greendash/GreenNavBar.jsx, src/js/components/pages/greendash/GreenRecommendation.tsx, src/js/components/pages/greendash/GreenRecsCreative.tsx, src/js/components/pages/greendash/GreenRecsPublisher.tsx, src/style/GreenRecommendations.less
- Publisher recs and creative recs are on separate sub-pages with a switcher at the top per Fiona's design
- Publisher recs pulled out to its own file & now uses new PropControlRange component (TODO: very slightly more chuggy when sliding through dense parts of the graph)
- Creative recs page can load existing analysis files & invoke MeasureServlet to execute new ones, but still needs breakdown widgets & recommendations engine pulled from the non-client-facing page
=> Green dashboard creative recommendations

src/js/components/pages/greendash/BreakdownCard.jsx, src/js/components/pages/greendash/emissionscalcTs.ts
Simple approach. 
If there is `tizen` in the by_os buckets, do one more query for just `os:tizen` and then split them into two rows:
not mobile: Samsung TV
mobile: Tizen
=> tizen spliting mobile

src/js/components/campaignpage/AdvertsCatalogue.jsx, src/js/components/campaignpage/CampaignPage.jsx, src/js/components/impact/ImpactOverviewPage.jsx, src/style/AdvertsCatalogue.less, src/style/CampaignPage.less, src/style/ImpactB2C.less, src/style/ImpactOverview.less
NB this isn't fixing show-stopping bugs, so don't worry about scrambling to get it fully tested for release. Just getting my local git cleaned up.
A little more complicated in some ways (now probes its container for available space & sets some utility classes to fix aspect ratio), overall should be simpler & more flexible.
Should now show at the right size in most contexts - places to test, off the top of my head:
- Impact Overview: the small preview card & the full-window modal
- Impact Stories: the ad preview in the phone frame
- Legacy campaign pages
=> Big cleanup of AdvertsCatalogue

src/js/components/pages/GreenLanding.jsx, src/js/components/pages/greendash/GreenNavBar.jsx, src/js/components/pages/greendash/emissionscalcTs.ts, src/style/GreenDashboard.less
Brands/agencies + their campaigns now have a link to the brands/agencies total impact on the greendash
@wongws11 I've made some edits to emissioncalcTs to allow 'getOffsetsByType' to just be given a list of campaigns rather than search a campaigns subcampaigns. This change shouldn't hopefully affect any existing code since the normal code path should remain the same (see new 'getOffsetsByType() -> getOffsetsByType2()) but if anything breaks soon you can blame me for it :)
=> Greendash impact page

src/js/components/pages/greendash/GreenRecsCreative.tsx
Recs lists are cached under a path derived from the analysed tag, the analysis manifest timestamp, and the option-set (retina, webp etc) they were generated under - previous code had some dodgy scoping that meant freshly-generated lists were stored under a stale path, so you'd see weird results when clicking around options.
=> Green recommendations: fix recommendation list caching

src/js/components/pages/greendash/GreenRecsCreative.tsx, src/style/GreenRecommendations.less
As before - scoping and object-identity issues meant that caching of previously-generated recommendation lists wasn't working perfectly, and multiple generate-recommendations processes were getting fired off at once.
Depends on matching PR https://github.com/good-loop/wwappbase.js/pull/207 in wwappbase.
=> Creative recommendations: fix caching paths

src/js/components/pages/greendash/GreenRecsCreative.tsx
- Filter function tries to fetch advertiser objects which don't always exist. Relax status to PUB_OR_DRAFT to cut some 404s on not-yet-published advertisers and set `swallow` flag to silence unavoidable errors.
- Filtering applies keyword-substring search to entire JSON string of the tag, which produces very counterintuitive results (matching internal field names etc). Restricted the match string to what the user can see on their screen: tag and brand name.
=> Creative optimisation page green-tag list filter tweaks

src/js/components/pages/greendash/GreenRecsCreative.tsx
Creative Recommendations bugfixes. As commit messages - fixes issues where:
- "Creative data breakdown" button appears when it shouldn't (because there's no manifest to source the breakdown)
- Analyse button doesn't lock while doing fresh analysis (clicking the Analyse button has a higher-level component show the "loading" spinner, meaning several sub-components get unmounted, lose their state, and remount forgetting they should be "loading")
- User with a slow system clock will see a fresh analysis saying e.g. "Done 30 seconds in the future"
=> Bugfix/2023 08/creative recs misc

src/js/components/impact/ImpactNavBars.jsx
The nav icons have no labels & need hover text - they're supposed to have it, but were set up using attribute "alt", which is explicitly intended to provide a stand-in for images, for accessibility and graceful-failure purposes. This PR changes them to use the "title" attribute.
=> Impact overview navbars alt --> title

src/js/components/pages/greendash/GreenRecsCreative.tsx
The problem happens when the user clicks from a one-tag view on the Metrics page to the creative recs page. Metrics uses URL filter params like `tag=xxxxx` while the Creative Recommendations ListLoad puts it in the path, as in `greendash/recommendation/creative/xxxxx`. The `tag` param currently takes priority - so clicking around the ListLoad changes the path, which is ignored.
This gives the path tag-ID priority over the URL parameter, so clicking around the list still works as expected when the param is present.
=> Green creative recs: Fix "can't switch tags" issue

src/js/components/impact/ImpactOverviewPage.jsx
Fixes some more issues with:
- Impact Overview page showing non-full-access users questionable data due to server-side post-filtering
- Impact Overview page putting listing crappy and broken charities as the "showcase" cards
Fixes to data access are mostly in https://github.com/good-loop/wwappbase.js/pull/262 - the first commit below just adds a `.value` destructuring to a call which used to return a value, but now returns a PV.
Charity fixes: the charities showcase just sorts biggest donations first before it displays.
=> Bugfix/2023 11/impact overview open access

src/js/components/campaignpage/CampaignPage.jsx, src/js/components/campaignpage/HowDoesItWork.jsx
client is frustrated with the "How it's done" text on their impact page. When digging into this, it turns out that detecting if a campaign is running or not hasn't been working for at least 7 months...
Now if a campaigns end date is in the future, the page will use present tense while it'll use past tense for prior campaigns.
=> prop call changed to method call

src/js/components/pages/greendash/MapCard.jsx
People complain that the downloaded version looks different - this is because we don't embed Tajawal.ttf in the SVG when generating it. Rather than doing that, let's get consistency by having the in-browser version use the same font (or at least one with very similar style, weight, metrics, since just about every computer has a Helvetica lookalike) as the downloadable file.
=> Green dashboard map card: label with basic sans-serif font
