runtest.js
Checks the server for production before running tests
=> Runtest changes to use gitlog.txt

src/js/components/campaignpage/CampaignPage.jsx, src/js/components/campaignpage/Charities.jsx
Adds a section to show charity registration numbers on the end of the charity cards
=> Charity details section

src/js/components/campaignpage/AdvertsCatalogue.jsx, src/js/components/campaignpage/CampaignPage.jsx, src/js/components/campaignpage/CampaignSplashCard.jsx, src/js/plumbing/ServerIO.js
Hello Ben
This PR refactors the CampaignPage.jsx to have a clearer loading stage, which fetches all the various data objects.
Have a check, comment/question if you want, then merge in.
It passes a smoke test, though it will probably break some stuff. But overall, should provide a basis for a more robust page.
- Dan
=> Feature/feb 2021/refactor campaign loading

src/js/components/campaignpage/AdvertsCatalogue.jsx, src/js/components/campaignpage/CampaignPage.jsx
Hello Ben -- this and a matching PR in `adserver` add support for hiding selected adverts.
=> hideAdverts

src/js/components/campaignpage/CampaignSplashCard.jsx
Like the commit description says. Pulled out the "decide what to call charity" logic to make it clearer & avoid an index-into-undefined bug.
=> Fix race-condition campaign page crash

GLAppManifest.js, package.json, src/js/components/ConsentWidget.jsx, src/js/components/MainDiv.jsx, src/js/components/NewTabMainDiv.jsx, src/js/components/NewtabLoginWidget.jsx, src/js/components/campaignpage/AdvertsCatalogue.jsx, src/js/components/cards/SignUpConnectCard.jsx, src/js/components/pages/AccountPage.jsx, src/js/components/pages/AccountSettings.jsx, src/js/components/pages/NewtabCharityLogin.jsx, src/js/components/pages/TabsForGoodSettings.jsx
Simplified My.GL and Person.js code to mostly work with a single profile.
Let's push the complexity of data sharing to the backend.
This is a matched PR with wwappbase.js
=> Bughunt/apr 2021/t4g

src/js/components/LandingSection.tsx, src/js/components/MyLoopNavBar.jsx, src/js/components/cards/SubscriptionBox.jsx, src/js/components/pages/AccountPage.jsx, src/js/components/pages/GetInvolvedPage.jsx, src/js/components/pages/MyCharitiesPage.jsx, src/js/components/pages/MyPage.jsx, web/img/LandingBackground/svg-desktop/infographic.svg, web/index.html
Adjustments according to `Website workshop tracker - Colin's suggestions`
=> Feature/jun 2021/tweaks

web/img/LandingBackground/svg-desktop/infographic-2.svg, web/img/LandingBackground/svg-desktop/infographic.svg
=> minor svg editing to center the viewpoint

src/js/components/pages/NewtabCharityLogin.jsx, src/style/main.less
@DanielRobertAppel will need your help to test if this work or not later this month. Thanks.
=> adding Subscribe checkbox to register box

src/js/components/NewTabMainDiv.jsx, src/js/components/NewtabTutorialCard.jsx, web/newtab.html
Still WIP, showing odd behaviour were general internet check can be shown as successful even when ethernet is pulled out. Functionality should be good though
=> Added general internet check and communication with parent iframe

.gitignore, pages/home.md, production.server.project.builder.sh, templates/footer.html, templates/navbar.html, templates/template.html, web/tabsforgood-landingpage.html
Let's work in master this time, so Fiona Amy and others can more easily see the edits.
=> Feature/2022 01/redesign

templates/template.html
I changed the name of the GTM file and updated it here.
=> Updating the link for GTM

src/js/components/NewTabMainDiv.jsx, src/style/NewTab.less
=> T4G - Layout adjustments

src/js/components/NewTabMainDiv.jsx, src/js/components/pages/TabsForGoodSettings.jsx
Turns out we had code to fetch all time, we just forgot to use it. Fetching all time data for tabsopen doesn't feel slow to me.
=> Feature/2022 08/better gettabsopen

src/js/components/MainDiv.jsx, src/js/components/NewTabMainDiv.jsx, src/js/components/mydata/MyDataDashboardHomeTab.jsx, src/js/components/mydata/MyDataDashboardPage.jsx, src/js/components/pages/CommonComponents.jsx, src/js/components/pages/GetInvolvedPage.jsx, src/js/components/pages/HomePage.jsx, src/js/components/pages/OurImpactPage.jsx, src/js/components/pages/TabsForGoodProductPage.jsx
As my.data is being put on pause as a product, removed all mentions of it on my.loop that I could find
=> removed all mentions of my.data that I could find

src/js/components/DateRangeWidget.js, src/js/components/pages/GreenDashboard.jsx, src/js/components/pages/greendash/GreenDashboardFilters.jsx, src/js/components/pages/greendash/GreenNavBar.jsx, src/js/components/pages/greendash/TimeSeriesCard.jsx, src/style/GreenDashboard.less, src/style/GreenMetrics.less
Rather than trying to merge almost a month of master-branch changes into the old greendash-mobile branch, I started a new one and copied the diffs manually.
Mobile functionality isn't 100% polished, but MUCH better than current master.
(Update: I never pushed the old greendash-mobile branch, which explains a lot.)
=> Green dashboard mobile redo

src/js/components/pages/greendash/TimeSeriesCard.jsx
Using boolean to track if ticks need to swap from kg to t.
=> use boolean to track ton > kg

src/js/components/pages/greendash/JourneyCardEmissions.jsx, src/js/components/pages/greendash/dashutils.js, src/style/GreenMetrics.less
Depends partly on wwappbase.js branch of same name which changes the button from a large "Download" text link to a small icon
=> Improve positioning/size of card-to-PNG export buttons

src/js/components/pages/greendash/BreakdownCardEmissions.jsx, src/js/components/pages/greendash/CompareCardEmissions.jsx, src/js/components/pages/greendash/GreenMetricsEmissions.jsx, src/js/components/pages/greendash/MapCardEmissions.jsx, src/js/components/pages/greendash/TimeSeriesCardEmissions.jsx, src/js/components/pages/greendash/emissionscalc.js, src/style/GreenMetrics.less, src/style/greendash-breakdown-card.less
All cards now respecting per1000 mode but certain sections still need removing.
=> Per-1000 dashboard final edits

src/js/components/campaignpage/CampaignPage.jsx
https://good-loop.monday.com/boards/2603585504/views/60487313/pulses/3431026924?userId=30055295
=> hide difference part if there is none

src/js/components/pages/greendash/dashutils.js
@geoffballinger Thanks for spotting the bug, this should be able to fix it.
=> periodFromUrl fix at the end of th month

src/js/components/DateRangeWidget.js, src/js/components/pages/greendash/GreenDashboardFilters.jsx, src/js/components/pages/greendash/dashutils.js, src/style/GreenDashboard.less
Fixed initial bugs with initial date setting, view centering and month label overlaps,
improved selection and general UI
=> Bugfix/2022 11/date range widget

.project, src/js/components/pages/BlogContent.jsx, src/js/components/pages/greendash/BreakdownCardEmissions.jsx, src/js/components/pages/greendash/GreenMetricsEmissions.jsx, src/js/components/pages/greendash/JourneyCardEmissions.jsx, src/js/components/pages/greendash/TimeOfDayCardEmissions.jsx
Last few tricks in lazy loading + coding style cleanup
=> Feature/2022 11/breakdowncard lazyload

src/java/com/goodloop/myloop/MetaHtmlServlet.java
MetaHtmlServlet now:
- Pre-fetches campaigns etc from the local/test/prod portal matching the prefix on the request URL (eg testmy --> testportal)
- Respects the "server" URL param, so server-side fetch will look on testportal for items if ?server=test is present
- Recovers more gracefully if the attempt to fetch items fails anyway - so the stray "$contents" placeholder is always removed.
=> Fix issues around fetching e.g. production campaign from test

src/js/components/campaignpage/CampaignModalTFG.jsx, src/style/CampaignPage.less
Hopefully reduces spacing enough to fit the modal onto smaller screens - can't replicate exactly so having to guess a bit.
=> Bugfix/2022 11/modal layout

src/js/components/campaignpage/CampaignSplashCard.jsx, src/style/CampaignPage.less, web/img/plus.svg
Also ripped out a LOT of CSS and restructured the splash page a little to make it possible to fix anything
=> Campaign page: Splash section mobile layout

src/js/components/pages/greendash/GreenDashboardFilters.jsx
Previous behaviour: you get to see items directly shared to you
New behaviour: you get to see items directly shared, plus items belonging to other direct shares (e.g. if an agency is shared to you, you can also see every brand assigned to it)
=> Green dashboard: more items in filter-by-x dropdown

package.json, src/js/components/pages/GreenDashboard.jsx, src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/GreenNavBar.jsx
Sharing for green dashboards.
Navbar styling is WIP. But that's minor & easy to fix.
=> Feature/2022 12/share

src/js/components/DateRangeWidget.js, src/style/DateRangeWidget.less, src/style/GreenDashboard.less
Styling tweaks + update to import LESS locally where it's used
=> DateRangeWidget refactor

src/js/components/MyLoginWidgetGuts.jsx, src/js/components/T4GSignUp.jsx, src/js/components/pages/CharityLandingPage.jsx, src/js/components/pages/SafariPage.jsx
Latest master `icon` repo has an SVG logo for Tabs For Good - this uses it.
=> Switch to SVG version of T4G logo

src/js/components/pages/greendash/BreakdownCard.jsx, src/js/components/pages/greendash/CompareCard.jsx, src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/MapCard.jsx, src/js/components/pages/greendash/TimeOfDayCard.jsx, src/js/components/pages/greendash/dashutils.js
Two new url params to use. 
1. `prob`. `prob=88` to use auto probability random sampling. `prob=1` to `prob=5` to force probability to be `0.1` to `0.5`; `prob=0` to turn off random sampler (It default to off anyway so not much use for this yet). 
2. `nocache`. `nocache=true` or `nocache=1` to enable no cache mode.
=> Feature/2023 01/random sampler

src/js/components/pages/greendash/CompareCard.jsx
comparing campaign emissions now shows name instead of id + chart shortens names down but keeps them on hover.
=> comparing campaign emissions now shows name instead of id

src/js/components/pages/greendash/BreakdownCard.jsx, src/js/components/pages/greendash/GreenMetrics.jsx
=> Feature/2023 01/greendash per1000 a

src/js/components/pages/GreenDashboard.jsx, src/js/components/pages/greendash/GreenDashboardFilters.jsx, src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/GreenNavBar.jsx
share btn integrated into the base account menu
Will also need to pull latest master in `wwappbase`
=> share button into account menu

src/js/components/TickerTotal.jsx
as per request from @laurenwilso to update base value & rate to more accurately reflect what we've raised so far
=> fix: t4g total raised now more accurate, based changed & rate adjusted

src/js/components/pages/greendash/BreakdownCard.jsx, src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/GreenRecommendation.tsx
step of the slider smaller > less dramatic change
=> smaller steps in slider

src/js/components/pages/greendash/emissionscalcTs.ts
=> directly query by agency

src/js/components/pages/greendash/BreakdownCard.jsx, src/js/components/pages/greendash/CompareCard.jsx, src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/MapCard.jsx
As mentioned in https://good-loop.monday.com/boards/2603585504/views/60487313/pulses/4289928028
Should be a safe fix but let's push it in next release, just to be extra safe.
=> auto handle if the response is nested in sampleing

src/js/components/pages/greendash/emissionscalcTs.ts
Just to cleanup the errors, nothing changed.
=> typescript cleanups

src/js/components/pages/greendash/GreenRecsPublisher.tsx
=> initCO2Cutoff

src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/GreenNavBar.jsx, src/style/GreenDashboard.less, src/style/greendash-breakdown-card.less
fix green dash layout issues by falling back to mobile view earlier.
=> green-navbar mobile fallback from md to xl

src/js/components/pages/greendash/GreenRecsPublisher.tsx
Also fix display issue where chart and allow/block list cards were trying to show meaningless data when the domain list was empty
=> Green recommendations / publishers: fix NPE on empty domain list

src/js/components/pages/greendash/BreakdownCard.jsx, src/js/components/pages/greendash/emissionscalcTs.ts
Better data bucket catching to fix per1000 bug
=> device type per1000 fix

src/js/components/pages/greendash/GreenNavBar.jsx, src/style/GreenDashboard.less, src/style/SideNavBar.less
Plus some refactoring in passing
=> Green dashboard: don't show the "Manage tags" link for pseudousers

src/js/components/pages/greendash/GreenRecsCreative.tsx
Picks up creative URLs on WeTransfer, Google Drive, Celtra Shareable Preview and Yahoo Sneak Peak & either stops analysis/recs entirely (general users) or displays a warning (us). Depends on https://github.com/good-loop/wwappbase.js/pull/209.
Also replaces the "data type breakdown" button with an "Analyse to see breakdown" message if a creative hasn't been analysed yet.
Green tags with "bad" URLs for testing:
WeTransfer https://localmy.good-loop.com/greendash/recommendation/creative/xeq6Qbjb
Yahoo https://testmy.good-loop.com/greendash/recommendation/creative/8cs91G3O
=> Creative recommendations: Flag "bad" creative preview URLs

src/js/components/impact/stories_components/StoriesComponents.jsx
imapct #1 now has both rows
prop names should actually work now
changed a donation description to be dev only when it's breaking since it heavily screws with layout otherwise
=> variable names fix + impact story row fix

config/localmy.good-loop.com.mac.nginx, config/localmy.good-loop.com.nginx
Bringing format and usage across multiple projects in line with the template in wwappbase.js. Symlinks added where files have been renamed.
=> Standardising local nginx config files

src/js/components/pages/greendash/BreakdownCard.jsx
=> format call

src/js/components/pages/greendash/GreenRecommendation.tsx, src/js/components/pages/greendash/GreenRecsCreative.tsx
Front-end counterpart to https://github.com/good-loop/adserver/pull/223
=> My-Loop specific front-end changes to match RecompressServlet overhaul

src/js/components/pages/greendash/BreakdownCard.jsx
The current format card in stage and production are broken. I found out the current way of fetching formats are not straight forward, yet we do have data directly from `by_format` buckets now. Why not use them directly? I hope this make sense.
=> simplfy - just use the data from the api call

src/js/components/pages/greendash/GreenRecsCreative.tsx
...but still flag discrepancies between auto-measured and manual in the overview.
Reasoning for this: https://good-loop.monday.com/boards/2603585504/pulses/4916673340
=> Creative recommendations: prefer manual weight if available

src/js/components/pages/greendash/BreakdownCard.jsx, src/js/components/pages/greendash/CompareCard.jsx, src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/TimeSeriesCard.jsx
@winterstein Benchmark data is now hardcoded in 0.5
How should i fetch benchmarks data?
=> Feature/2023 10/greendata benchmarks

src/js/components/pages/greendash/AdtechBreakdownCard.jsx, src/js/components/pages/greendash/BreakdownCard.jsx, src/js/components/pages/greendash/GreenMetrics.jsx, src/js/components/pages/greendash/emissionscalcTs.ts
1. Move Adtech breakdown card as its own card as requested. 
2. Change the way breakdown calls data. Now it will do all of the call async, which result in a much faster loading time.
=> Feature/2023 10/adtech card

src/js/components/MainDiv.jsx
Remove Login widget and account menu on the front page of my loop
=> Feature/2023 10/remove public login register

src/js/components/NewTabMainDiv.jsx
=> Feature/2024 01/t4g sunset
